name: checking terraoform code

runs:
  using: "composite"
    steps:
      - name: fmt
        run: terraform fmt -check

      - name: init
        run: terraform init

      - name: validate
        run: terraform validate

      - name: plan
        id: plan
        run: terraform plan -no-color
