name: checking terraoform code

inputs:
  terraform-version:
    default: '1.0.5'
    required: true
  working-dir:
    default: ./env/stg
    required: true

outputs:
  execution-plan:
    value: ${{ steps.plan.outputs.stdout }}

runs:
  using: "composite"
  steps:
    - name: set up terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: fmt
      shell: bash
      run: |
        echo ::group:: recursive checking format
        terraform fmt -recursive -check
        echo ::endgroup::

    - name: init
      shell: bash
      run: |
        echo ::group:: init
        terraform init
        echo ::endgroup::
      working-directory: ${{ inputs.working-dir }}

    - name: validate
      shell: bash
      run: |
        echo ::group:: validate
          terraform validate
        echo ::endgroup
      working-directory: ${{ inputs.working-dir }}

    - name: plan
      id: plan
      shell: bash
      run: |
        echo ::group:: execution plan
        terraform plan -no-color
        echo ::endgroup::
      working-directory: ${{ inputs.working-dir }}
