name: checking terraoform code

inputs:
  terraform-version:
    default: '1.0.5'
    required: true
  working-dir:
    default: ./env/stg
    required: true

outputs:
  execution-plan:
    value: ${{ steps.plan.outputs.stdout }}

runs:
  using: "composite"
  steps:
    - name: set up terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: fmt
      shell: terraform fmt -recursive -check

    - name: init
      shell: terraform init
      working-directory: ${{ inputs.working-dir }}

    - name: validate
      shell: terraform validate
      working-directory: ${{ inputs.working-dir }}

    - name: plan
      id: plan
      shell: terraform plan -no-color
      working-directory: ${{ inputs.working-dir }}
