name: checking terraoform code

inputs:
  terraform-version:
    default: '1.0.5'
    required: true

runs:
  using: "composite"
    steps:
      - name: seet up terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: fmt
        run: terraform fmt -check

      - name: init
        run: terraform init

      - name: validate
        run: terraform validate

      - name: plan
        id: plan
        run: terraform plan -no-color
