name: checking terraoform code
description: steps execute fmt, init, validate and plan

inputs:
  terraform-version:
    default: '1.0.5'
    description: terraform version
    required: true
  working-dir:
    default: ./env/stg
    description: directory to run in
    required: true

outputs:
  execution-plan:
    description: execution plan
    value: ${{ steps.plan.outputs.stdout }}

runs:
  using: "composite"
  steps:
    - name: set up terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: fmt
      shell: bash
      run: terraform fmt -recursive -check

    - name: init
      shell: bash
      run: terraform init
      working-directory: ${{ inputs.working-dir }}

    - name: validate
      shell: bash
      run: terraform validate
      working-directory: ${{ inputs.working-dir }}

    - name: plan
      id: plan
      shell: bash
      run: terraform plan -no-color
      working-directory: ${{ inputs.working-dir }}
