name: checking terraoform code

inputs:
  terraform-version:
    default: '1.0.5'
    required: true
  working-dir:
    default: ./env/stg
    required: true

outputs:
  execution-plan:
    value: ${{ steps.plan.outputs.stdout }}

runs:
  using: "composite"
  steps:
    - name: set up terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: fmt
      shell: bash
      run: |
        ::group:: recursive checking format
          terraform fmt -recursive -check
        ::endgroup::

    - name: init
      shell: bash
      run: |
        ::group:: init
          terraform init
        ::endgroup::
      working-directory: ${{ inputs.working-dir }}

    - name: validate
      shell: bash
      run: |
        ::group:: validate
          terraform validate
        ::endgroup
      working-directory: ${{ inputs.working-dir }}

    - name: plan
      id: plan
      shell: bash
      run: |
        ::group:: execution plan
          terraform plan -no-color
        ::endgroup::
      working-directory: ${{ inputs.working-dir }}
