name: terraform apply

on:
  workflow_dispatch:
    inputs:
      enviroment:
        type: environment

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      TERRAFORM-DIR: ./env/${{ github.event.inputs.environment }}

    steps:
      - name: check out source
        uses: actions/checkout@v2

      - name: set up terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.5'

      - name: init
        run: terraform init
        working-directory: ${{ env.TERRAFORM-DIR }}

      - name: apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.TERRAFORM-DIR }}
