name: terraform apply

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: check out source
        uses: actions/checkout@v3

      - name: setup target terraform dir
        id: tf-dir
        uses: ./.github/actions/target-terraform-dir
        with:
          target-env: ${{ github.event.inputs.environment }}

      - name: set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.0.5'

      - name: init
        run: terraform init
        working-directory: ${{steps.tf-dir.outputs.target-dir}}

      - name: apply
        run: terraform apply -auto-approve
        working-directory: ${{steps.tf-dir.outputs.target-dir}}
