name: terraform plan

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: ./env/${{ github.event.inputs.environment }}
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5

      - name: init
        run: terraform init

      - name: plan
        id: plan
        run: terraform plan

      - name: print result
        run: |
          echo ${{ steps.plan.outputs.stdout }}
