name: terraform plan

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v3

      - name: setup target terraform dir
        id: tf-dir
        uses: ./.github/actions/target-terraform-dir
        with:
          target-env: ${{ github.event.inputs.environment }}

      - name: plan after check
        id: composite-plan
        uses: ./.github/actions/composite-plan
        with:
          terraform-version: '1.0.5'
          working-dir: ${{steps.tf-dir.outputs.target-dir}}
