name: terraform plan

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: plan after check
        id: composite-plan
        uses: ./.github/actions/composite-plan
        with:
          terraform-version: '1.0.5'
          working-dir: ./env/${{ github.event.inputs.environment }}

      - name: print result
        run: echo ${{ steps.composite-plan.outputs.execution-plan }}
