name: terraform plan

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      terraform-dir: ./${{ github.event.inputs.environment }}
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5

      - name: terraform init
        run: terraform init
        working-directory: ${{ env.terraform-dir }}

      - name: teraform plan
        id: plan
        run: terraform plan
        working-directory: ${{ env.terraform-dir }}

      - name: print result
        run: |
          echo ${{ steps.plan.outputs.stdout }}
          echo ${{ steps.plan.outputs.stderr }}
          echo ${{ steps.plan.outputs.exitcode }}




